### PR TITLE
fixing Pending Confirmations count (#133)

### LINKED ISSUE #133: Pending Confirmations count is broken
After sending a transaction, the pending confirmation count does not make any sense

### PR DESCRIPTION
**Pull request by jellehelsen**
This fixes #133. Or at least the visual representation problem, number of confirmations count correctly now but outgoing transactions seem to stay pending (even after 130 confirmations). 

Testnet transaction I used for testing: 209d05f389498591a4955ff87a5370c9b74ad1f1ae581b5d5011f2f80fe60022
image

### CODE REVIEW

**Comment by pacu** [comment]
Pending transactions should be cleared after 10 confirmations. that's weird.

**Comment by jellehelsen** [comment]
I suspect this is a bug in ZcashLightClientKit's SDKSynchronizer. The transactions stays in synchronizer.allPendingTransactions .

**Comment by pacu** [comment]
probably a race condition. I'll open a new bug for that on the repo

File: wallet/wallet/Environment/CombineSynchronizer.swift [hunk 1]
```diff
@@ -229,13 +223,13 @@ extension DetailModel {
         self.shielded = pendingTransaction.toAddress.isValidShieldedAddress
         self.status = .paid(success: pendingTransaction.isSubmitSuccess)
         if pendingTransaction.expiryHeight > 0, let latest = latestBlockHeight {
-            self.subtitle = "\(abs(latest - pendingTransaction.expiryHeight - ZcashSDK.EXPIRY_OFFSET)) of 10 Confirmations"
+            self.subtitle = "\(abs(latest - (pendingTransaction.expiryHeight - ZcashSDK.EXPIRY_OFFSET))) Confirmations"
```
Comment (pacu) [inline wallet/wallet/Environment/CombineSynchronizer.swift:226]: I've seen that there's an conceptual mistake there I made at the time.

confirmations should be counted with minedHeight. probably was a workaround because of a fixed bug on the sdk where the mined height was not populated properly. Could you make this change
```
  /**
     height which the block was mined at.
     -1 when block has not been mined yet
     */
    var minedHeight: BlockHeight { get set }
```

**Comment by pacu** [comment]
I see that it says "Unsent transaction" that means that the transaction failed to send. that's something different than pending transactions having the wrong count. Unsent transaction shouidn't clear up (we haven't decided what to do with them), and **they definitely shouldn't have a pending count**

File: wallet/wallet/Environment/CombineSynchronizer.swift (hunk 1 above)
Comment (jellehelsen) [reply wallet/wallet/Environment/CombineSynchronizer.swift]: I've implemented the changes you requested, but was unable to test them. Wallet stop synchronising completely, so I can't get any coins in to make an outgoing transaction. Also, the wallet always create the same new address. The address even stays the same when switching from TESTNET to MAINNET.

**Comment by jellehelsen** [comment]
The transaction was definitely sent, I checked on https://explorer.testnet.z.cash/tx/209d05f389498591a4955ff87a5370c9b74ad1f1ae581b5d5011f2f80fe60022 . Also the transaction is of the PendingTransactionEntity class. That's why I believe the SDK thinks it is pending.

File: wallet/wallet/Environment/CombineSynchronizer.swift (hunk 1 above)
Comment (pacu) [reply wallet/wallet/Environment/CombineSynchronizer.swift]: > Wallet stop synchronising completely, so I can't get any coins in to make an outgoing transaction. 
Can you elaborate a little bit more on this? 

> Also, the wallet always create the same new address. The address even stays the same when switching from TESTNET to MAINNET.

Yes, I've experienced this. It's difficult to dribble all three levels of build caches: Xcode (master of caching stuff), Cocoapods and Cargo. I have a troubleshooting guide pending to do, I'll add that to our backlog. Thanks.

What I do to switch networks is to do this:
1. set ZCASH_NETWORK_ENVIRONMENT to the desired type
2. delete /Pods
  a. If working on SDK at a local level, delete these files:
    * `target/` folder
    * `ZcashLightClientKit/zcashlc/*.a`
    * `lib/*.a`
3. Backup seeds if needed, then Nuke wallet
4. Clean Xcode
5. close Xcode
6. pod install
7. open xcode
8. build app

**Comment by pacu** [comment]
> The transaction was definitely sent, I checked on https://explorer.testnet.z.cash/tx/209d05f389498591a4955ff87a5370c9b74ad1f1ae581b5d5011f2f80fe60022 . Also the transaction is of the PendingTransactionEntity class. That's why I believe the SDK thinks it is pending.

This will be solved by the "Data API" feature of librustzcash and our SDKs in a few months. Handling pending transactions is really a pain because we have to keep track of this extra database, and for the case of unconfirmed transactions, there's a duplication of entries that we need to account for and do proper book keeping. I opened an issue on the ZcashLightClientKit about this.

File: wallet/wallet/Environment/CombineSynchronizer.swift (hunk 1 above)
Comment (jellehelsen) [reply wallet/wallet/Environment/CombineSynchronizer.swift]: Thanks for your tips. Sync works again and I tested the change. Now there is another problem. The minedHeight remains at -1. Is this always the case with PendingTransactionEntity? Anyway, this means that the if statement is always false. In the previous solution the if statement is almost always true. Unless you nuke the wallet and restore it. But by the time it resyncs it is seen as a confirmed transaction.
So now it looks like this:
image
until you nuke and restore. After the sync it looks like this:
image

I think the code is correct and ready to merge, but there is no way to really see it in action due to bugs in the SDK.
